name: on release published
on:
  release:
    types: [published]
# https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      # debug
      - run: echo "${{ toJSON(github.event) }}"
      - run: echo "${{ toJSON(github.event.release) }}"
      - run: echo "${{ github.event.release.tag_name }}"
      - run: |
          echo "awesome release"
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.DACBD_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/dacbd/err/dispatches \
            -d '{"event_type":"trigger-test", "client_payload": {"environment":"REPODIS", "tag":"${{ github.event.release.tag_name }}"} }'
